services:
  loe-scraper:
    build: .               # ← вместо image: берём из текущей папки
    container_name: loe-scraper
    restart: "no"
    env_file:
      - .env
    volumes:
      - .:/app             # ← монтируем текущую папку → код всегда свежий
    # command: ["python", "scraper.py"]   # можно оставить в Dockerfile, либо переопределить здесь
